services:
  postgres:
    image: postgres:15
    container_name: restaurant_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant_db
    ports:
      - "5432:5432"
    volumes:
      - restaurant_postgres_data:/var/lib/postgresql/data

volumes:
  restaurant_postgres_data:

